# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ffmpeg_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'Masonry', '~> 1.1.0'
   
   # MPMCategory 美平米基础库
   # pod 'MPMCategory', :git => 'http://120.26.216.233/ios/MPMCategory.git'

  # Pods for ffmpeg_demo

end
